In [1]:
import pandas as pd
import numpy as np

In [2]:
test = pd.read_csv(r'E:\updateresumeprojects\SQL+pandaspipeline project\Raw dataset\transactions_test.csv')
train = pd.read_csv(r'E:\updateresumeprojects\SQL+pandaspipeline project\Raw dataset\transactions_train.csv')

In [3]:
test.head(5)

,transaction_id,transaction_time,customer_id,merchant_id,account_age_days,credit_score_band,kyc_level,avg_monthly_spend,merchant_risk_score,transaction_amount,...,device_type,is_international,ip_risk_score,txn_count_1h,txn_count_24h,failed_txn_count_24h,geo_distance_from_last_txn,amount_deviation_from_user_mean,is_fraud,post_auth_risk_score
0,305461,02:41.6,11453,7397,1417,4,2,7549.746993,0.056340,1783.564199,...,mobile,0,0.417366,1,2,0,54.226534,1531.905966,0,0.358507
1,341279,06:25.5,28021,97,830,2,2,2766.322082,0.736960,7038.755549,...,mobile,0,0.272247,1,3,1,60.728405,6946.544813,0,0.065886
2,344364,07:50.8,2269,2796,1651,2,3,3988.151593,0.454618,663.057016,...,mobile,0,0.446442,3,3,0,102.171038,530.118629,0,0.026225
3,84227,17:11.8,32373,787,1207,1,2,5472.122178,0.417973,1665.509484,...,desktop,0,0.308703,2,3,0,10.146806,1483.105412,0,0.201940
4,187825,19:50.8,13548,4439,1926,5,2,1758.784635,0.535169,1524.306346,...,mobile,1,0.305401,2,1,1,18.328551,1465.680191,0,0.234395

In [4]:
train.head(5)

,transaction_id,transaction_time,customer_id,merchant_id,account_age_days,credit_score_band,kyc_level,avg_monthly_spend,merchant_risk_score,transaction_amount,...,device_type,is_international,ip_risk_score,txn_count_1h,txn_count_24h,failed_txn_count_24h,geo_distance_from_last_txn,amount_deviation_from_user_mean,is_fraud,post_auth_risk_score
0,359131,2023-01-01 00:02:00.328105993,11102,2282,284,2,3,6091.747132,0.456269,2408.320473,...,desktop,0,0.142532,1,3,1,33.458018,2205.262235,0,0.099920
1,351207,2023-01-01 00:02:26.339769237,22891,3016,1363,2,3,3794.044563,0.449021,2765.255095,...,mobile,0,0.131811,0,5,0,3.375083,2638.786943,0,0.291715
2,10209,2023-01-01 00:06:54.145825305,3102,1855,1318,5,2,6697.058451,0.220252,1529.079168,...,desktop,0,0.322137,0,5,0,13.732603,1305.843886,0,0.216647
3,62660,2023-01-01 00:06:57.723185583,4041,2525,1914,1,1,2906.711704,0.202223,610.407487,...,mobile,0,0.171764,1,2,0,18.840187,513.517097,0,0.354154
4,384254,2023-01-01 00:08:05.487541188,3979,1555,360,2,3,5082.651983,0.171230,986.397163,...,mobile,0,0.248766,1,1,0,15.344375,816.975430,0,0.149084

In [5]:
train.shape

(300113, 21)

In [6]:
test.shape

(99887, 21)

In [7]:
master_transaction = pd.concat([train,test],ignore_index = True)

In [8]:
master_transaction.shape

(400000, 21)

In [9]:
master_transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 21 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   transaction_id                   400000 non-null  int64
 1   transaction_time                 400000 non-null  object
 2   customer_id                      400000 non-null  int64
 3   merchant_id                      400000 non-null  int64
 4   account_age_days                 400000 non-null  int64
 5   credit_score_band                400000 non-null  int64
 6   kyc_level                        400000 non-null  int64
 7   avg_monthly_spend                400000 non-null  float64
 8   merchant_risk_score              400000 non-null  float64
 9   transaction_amount               400000 non-null  float64
 10  payment_channel                  400000 non-null  object
 11  device_type                      400000 non-null  object
 12  is_international                 400000 non-null  int64
 13  ip_risk_score                    400000 non-null  float64
 14  txn_count_1h                     400000 non-null  int64
 15  txn_count_24h                    400000 non-null  int64
 16  failed_txn_count_24h             400000 non-null  int64
 17  geo_distance_from_last_txn       400000 non-null  float64
 18  amount_deviation_from_user_mean  400000 non-null  float64
 19  is_fraud                         400000 non-null  int64
 20  post_auth_risk_score             400000 non-null  float64
dtypes: float64(7), int64(11), object(3)
memory usage: 64.1+ MB

In [10]:
master_transaction.isnull().sum()

transaction_id                     0
transaction_time                   0
customer_id                        0
merchant_id                        0
account_age_days                   0
credit_score_band                  0
kyc_level                          0
avg_monthly_spend                  0
merchant_risk_score                0
transaction_amount                 0
payment_channel                    0
device_type                        0
is_international                   0
ip_risk_score                      0
txn_count_1h                       0
txn_count_24h                      0
failed_txn_count_24h               0
geo_distance_from_last_txn         0
amount_deviation_from_user_mean    0
is_fraud                           0
post_auth_risk_score               0
dtype: int64

In [11]:
# so there are no nulls found in the dataset

In [12]:
master_transaction.duplicated().sum()

np.int64(0)

### whole rows are not duplicate

In [13]:
# and no duplicates found so no need of removing duplicates and nulls

In [14]:
master_transaction.head(10)

,transaction_id,transaction_time,customer_id,merchant_id,account_age_days,credit_score_band,kyc_level,avg_monthly_spend,merchant_risk_score,transaction_amount,...,device_type,is_international,ip_risk_score,txn_count_1h,txn_count_24h,failed_txn_count_24h,geo_distance_from_last_txn,amount_deviation_from_user_mean,is_fraud,post_auth_risk_score
0,359131,2023-01-01 00:02:00.328105993,11102,2282,284,2,3,6091.747132,0.456269,2408.320473,...,desktop,0,0.142532,1,3,1,33.458018,2205.262235,0,0.099920
1,351207,2023-01-01 00:02:26.339769237,22891,3016,1363,2,3,3794.044563,0.449021,2765.255095,...,mobile,0,0.131811,0,5,0,3.375083,2638.786943,0,0.291715
2,10209,2023-01-01 00:06:54.145825305,3102,1855,1318,5,2,6697.058451,0.220252,1529.079168,...,desktop,0,0.322137,0,5,0,13.732603,1305.843886,0,0.216647
3,62660,2023-01-01 00:06:57.723185583,4041,2525,1914,1,1,2906.711704,0.202223,610.407487,...,mobile,0,0.171764,1,2,0,18.840187,513.517097,0,0.354154
4,384254,2023-01-01 00:08:05.487541188,3979,1555,360,2,3,5082.651983,0.171230,986.397163,...,mobile,0,0.248766,1,1,0,15.344375,816.975430,0,0.149084
5,204870,2023-01-01 00:09:11.294695623,1941,6085,1340,2,3,2794.089778,0.137590,1780.932827,...,desktop,0,0.350444,0,1,0,47.455146,1687.796501,0,0.290511
6,18970,2023-01-01 00:10:05.075100599,33828,1973,990,4,1,613.349748,0.219365,4478.461175,...,mobile,0,0.439570,2,5,0,16.540104,4458.016183,0,0.220386
7,176662,2023-01-01 00:11:53.896526457,17049,5736,514,2,2,3101.746461,0.488389,764.891641,...,mobile,0,0.343399,0,2,1,41.820558,661.500092,0,0.032760
8,283534,2023-01-01 00:13:23.350519980,31559,2485,1010,5,2,2618.498633,0.179048,516.009939,...,mobile,0,0.213008,0,6,0,27.372305,428.726651,0,0.008795
9,139169,2023-01-01 00:13:31.431162139,35852,1281,1573,5,2,10289.326011,0.124543,430.208442,...,mobile,0,0.386016,2,2,0,0.175297,87.230908,0,0.293279

In [15]:
master_transaction['transaction_time'].unique()[:20]

array(['2023-01-01 00:02:00.328105993', '2023-01-01 00:02:26.339769237',
       '2023-01-01 00:06:54.145825305', '2023-01-01 00:06:57.723185583',
       '2023-01-01 00:08:05.487541188', '2023-01-01 00:09:11.294695623',
       '2023-01-01 00:10:05.075100599', '2023-01-01 00:11:53.896526457',
       '2023-01-01 00:13:23.350519980', '2023-01-01 00:13:31.431162139',
       '2023-01-01 00:14:23.758032664', '2023-01-01 00:15:40.330125217',
       '2023-01-01 00:15:55.959668748', '2023-01-01 00:16:24.930253883',
       '2023-01-01 00:18:55.934435747', '2023-01-01 00:20:02.556450316',
       '2023-01-01 00:21:00.413735389', '2023-01-01 00:21:05.644580671',
       '2023-01-01 00:21:21.695931992', '2023-01-01 00:22:19.465790756'],
      dtype=object)

In [16]:
# Only need to fix  transaction_time column to datetime and it contains mixed format some are datetime some are only time

In [17]:
master_transaction['transaction_time'] = pd.to_datetime(master_transaction['transaction_time'],format = 'mixed',errors = 'coerce')

In [18]:
master_transaction['transaction_time'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 400000 entries, 0 to 399999
Series name: transaction_time
Non-Null Count   Dtype
--------------   -----
340121 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 3.1 MB

In [19]:
master_transaction['transaction_time'].isnull().sum()  #there are some nulls in transaction time but we will filter out them in sql

np.int64(59879)

In [20]:
master_transaction['transaction_id'].duplicated().sum() # this column does not have duplicates which mean no duplicated or wrong transaction
#other rows like customer_id,merchant_id can have duplicates

np.int64(0)

In [21]:
master_transaction[master_transaction['transaction_amount'] < 0] # no negative transactions

Empty DataFrame
Columns: [transaction_id, transaction_time, customer_id, merchant_id, account_age_days, credit_score_band, kyc_level, avg_monthly_spend, merchant_risk_score, transaction_amount, payment_channel, device_type, is_international, ip_risk_score, txn_count_1h, txn_count_24h, failed_txn_count_24h, geo_distance_from_last_txn, amount_deviation_from_user_mean, is_fraud, post_auth_risk_score]
Index: []

[0 rows x 21 columns]

In [22]:
master_transaction['customer_id'].value_counts()

customer_id
18600    25
30715    25
15949    24
26459    24
35035    24
         ..
8659      1
20971     1
37094     1
21780     1
34083     1
Name: count, Length: 39999, dtype: int64

In [23]:
master_transaction['merchant_id'].value_counts()

merchant_id
2753    85
7832    79
4237    79
131     77
7926    77
        ..
1000    29
1493    29
6497    29
4697    28
5723    28
Name: count, Length: 8000, dtype: int64

In [24]:
master_transaction['hour'] = master_transaction['transaction_time'].dt.hour

In [25]:
master_transaction['day_number'] = master_transaction['transaction_time'].dt.dayofweek
master_transaction['day_name']  = master_transaction['transaction_time'].dt.day_name()

In [26]:
master_transaction['month_name'] = master_transaction['transaction_time'].dt.month_name()

In [27]:
def day_type(day_name):
    if (day_name == 'Sunday') or (day_name == 'Saturday'):
        return 'Weekend'
    else:
        return 'Weekday'
master_transaction['day_type']  = master_transaction['day_name'].apply(day_type)

In [28]:
master_transaction[['day_name','day_type']].value_counts()

day_name   day_type
Wednesday  Weekday     82970
Thursday   Weekday     43267
Tuesday    Weekday     42958
Sunday     Weekend     42880
Monday     Weekday     42721
Friday     Weekday     42690
Saturday   Weekend     42635
Name: count, dtype: int64

In [29]:
master_transaction['post_auth_risk_score'].describe()

count    400000.000000
mean          0.211365
std           0.142771
min           0.000001
25%           0.102100
50%           0.203767
75%           0.305576
max           0.999988
Name: post_auth_risk_score, dtype: float64

In [30]:
master_transaction[['transaction_amount','account_age_days','txn_count_1h','txn_count_24h','amount_deviation_from_user_mean','failed_txn_count_24h']].describe()

,transaction_amount,account_age_days,txn_count_1h,txn_count_24h,amount_deviation_from_user_mean,failed_txn_count_24h
count,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000,400000.000000
mean,2402.199019,1016.729042,1.099865,3.199785,2235.803865,0.350517
std,1699.753929,571.850184,1.047955,1.787659,1702.898229,0.592263
min,2.582327,30.000000,0.000000,0.000000,-778.603491,0.000000
25%,1153.761675,519.000000,0.000000,2.000000,987.995149,0.000000
50%,2016.287577,1017.000000,1.000000,3.000000,1852.843161,0.000000
75%,3230.034207,1514.000000,2.000000,4.000000,3066.790637,1.000000
max,19486.987108,1999.000000,9.000000,15.000000,19419.022461,6.000000

In [31]:
def customer_tenure(account_age_days):
    if account_age_days<=90:
        return 'New Customer'
    elif 91<=account_age_days<=365:
        return 'Growing Customer'
    elif 366<= account_age_days<=730:
        return 'Loyal Customer'
    else: 
        return 'Long Term Customer'
master_transaction['customer_tenure_segment'] = master_transaction['account_age_days'].apply(customer_tenure)

In [32]:
master_transaction['customer_tenure_segment'].value_counts()

customer_tenure_segment
Long Term Customer    257147
Loyal Customer         74100
Growing Customer       55843
New Customer           12910
Name: count, dtype: int64

In [33]:
def transaction_size(transaction_amount):
    if transaction_amount <1154:
        return 'Small'
    elif 1154<=transaction_amount<2017:
        return 'Medium'
    elif 2017<=transaction_amount<3231:
        return 'Large'
    else:
        return 'premium'
master_transaction['transaction_size_segment'] = master_transaction['transaction_amount'].apply(transaction_size)

In [34]:
master_transaction['transaction_size_segment'].value_counts()

transaction_size_segment
Medium     100037
Small      100035
Large       99993
premium     99935
Name: count, dtype: int64

In [35]:
def spending(amount_deviation_from_user_mean):
    if amount_deviation_from_user_mean <=0:
        return 'Less than normal spending' 
    elif 0 < amount_deviation_from_user_mean <1000:
        return 'Normal spend'
    elif 1000<=amount_deviation_from_user_mean<3000:
        return 'Unusual spend'
    else:
        return 'High deviation spend'
master_transaction['spending_segment'] = master_transaction['amount_deviation_from_user_mean'].apply(spending)

In [36]:
master_transaction['spending_segment'].value_counts()

spending_segment
Unusual spend                194350
High deviation spend         104142
Normal spend                  96841
Less than normal spending      4667
Name: count, dtype: int64

In [37]:
master_transaction.head(10)

,transaction_id,transaction_time,customer_id,merchant_id,account_age_days,credit_score_band,kyc_level,avg_monthly_spend,merchant_risk_score,transaction_amount,...,is_fraud,post_auth_risk_score,hour,day_number,day_name,month_name,day_type,customer_tenure_segment,transaction_size_segment,spending_segment
0,359131,2023-01-01 00:02:00.328105993,11102,2282,284,2,3,6091.747132,0.456269,2408.320473,...,0,0.099920,0.0,6.0,Sunday,January,Weekend,Growing Customer,Large,Unusual spend
1,351207,2023-01-01 00:02:26.339769237,22891,3016,1363,2,3,3794.044563,0.449021,2765.255095,...,0,0.291715,0.0,6.0,Sunday,January,Weekend,Long Term Customer,Large,Unusual spend
2,10209,2023-01-01 00:06:54.145825305,3102,1855,1318,5,2,6697.058451,0.220252,1529.079168,...,0,0.216647,0.0,6.0,Sunday,January,Weekend,Long Term Customer,Medium,Unusual spend
3,62660,2023-01-01 00:06:57.723185583,4041,2525,1914,1,1,2906.711704,0.202223,610.407487,...,0,0.354154,0.0,6.0,Sunday,January,Weekend,Long Term Customer,Small,Normal spend
4,384254,2023-01-01 00:08:05.487541188,3979,1555,360,2,3,5082.651983,0.171230,986.397163,...,0,0.149084,0.0,6.0,Sunday,January,Weekend,Growing Customer,Small,Normal spend
5,204870,2023-01-01 00:09:11.294695623,1941,6085,1340,2,3,2794.089778,0.137590,1780.932827,...,0,0.290511,0.0,6.0,Sunday,January,Weekend,Long Term Customer,Medium,Unusual spend
6,18970,2023-01-01 00:10:05.075100599,33828,1973,990,4,1,613.349748,0.219365,4478.461175,...,0,0.220386,0.0,6.0,Sunday,January,Weekend,Long Term Customer,premium,High deviation spend
7,176662,2023-01-01 00:11:53.896526457,17049,5736,514,2,2,3101.746461,0.488389,764.891641,...,0,0.032760,0.0,6.0,Sunday,January,Weekend,Loyal Customer,Small,Normal spend
8,283534,2023-01-01 00:13:23.350519980,31559,2485,1010,5,2,2618.498633,0.179048,516.009939,...,0,0.008795,0.0,6.0,Sunday,January,Weekend,Long Term Customer,Small,Normal spend
9,139169,2023-01-01 00:13:31.431162139,35852,1281,1573,5,2,10289.326011,0.124543,430.208442,...,0,0.293279,0.0,6.0,Sunday,January,Weekend,Long Term Customer,Small,Normal spend

In [38]:
from sqlalchemy import create_engine

In [39]:
engine = create_engine("mysql+pymysql://root:Pankaj%4000789@localhost/transactions_tables")

In [40]:
master_transaction.to_sql(
    name='transactions_master',
    con=engine,
    if_exists='replace',
    index=False
)

400000

In [41]:
pd.read_sql("select count(*) from transactions_master ;" ,engine) # to confirm that table has loaded perfectly

   count(*)
0    400000

In [42]:
# to check duplicate transaction ids

In [43]:
pd.read_sql("SELECT transaction_id,COUNT(*) FROM transactions_master GROUP BY transaction_id HAVING COUNT(*) > 1 ;",engine)

Empty DataFrame
Columns: [transaction_id, COUNT(*)]
Index: []

In [44]:
#checking nulls using sql

In [45]:
pd.read_sql("SELECT * FROM transactions_master WHERE transaction_id IS NULL ;",engine)

Empty DataFrame
Columns: [transaction_id, transaction_time, customer_id, merchant_id, account_age_days, credit_score_band, kyc_level, avg_monthly_spend, merchant_risk_score, transaction_amount, payment_channel, device_type, is_international, ip_risk_score, txn_count_1h, txn_count_24h, failed_txn_count_24h, geo_distance_from_last_txn, amount_deviation_from_user_mean, is_fraud, post_auth_risk_score, hour, day_number, day_name, month_name, day_type, customer_tenure_segment, transaction_size_segment, spending_segment]
Index: []

[0 rows x 29 columns]

In [46]:
 pd.read_sql("SELECT * FROM transactions_master WHERE customer_id IS NULL ;",engine)

Empty DataFrame
Columns: [transaction_id, transaction_time, customer_id, merchant_id, account_age_days, credit_score_band, kyc_level, avg_monthly_spend, merchant_risk_score, transaction_amount, payment_channel, device_type, is_international, ip_risk_score, txn_count_1h, txn_count_24h, failed_txn_count_24h, geo_distance_from_last_txn, amount_deviation_from_user_mean, is_fraud, post_auth_risk_score, hour, day_number, day_name, month_name, day_type, customer_tenure_segment, transaction_size_segment, spending_segment]
Index: []

[0 rows x 29 columns]

In [47]:
pd.read_sql("SELECT * FROM transactions_master WHERE merchant_id IS NULL ;",engine)

Empty DataFrame
Columns: [transaction_id, transaction_time, customer_id, merchant_id, account_age_days, credit_score_band, kyc_level, avg_monthly_spend, merchant_risk_score, transaction_amount, payment_channel, device_type, is_international, ip_risk_score, txn_count_1h, txn_count_24h, failed_txn_count_24h, geo_distance_from_last_txn, amount_deviation_from_user_mean, is_fraud, post_auth_risk_score, hour, day_number, day_name, month_name, day_type, customer_tenure_segment, transaction_size_segment, spending_segment]
Index: []

[0 rows x 29 columns]

In [48]:
pd.read_sql("SELECT * FROM transactions_master WHERE is_fraud IS NULL ;",engine)

Empty DataFrame
Columns: [transaction_id, transaction_time, customer_id, merchant_id, account_age_days, credit_score_band, kyc_level, avg_monthly_spend, merchant_risk_score, transaction_amount, payment_channel, device_type, is_international, ip_risk_score, txn_count_1h, txn_count_24h, failed_txn_count_24h, geo_distance_from_last_txn, amount_deviation_from_user_mean, is_fraud, post_auth_risk_score, hour, day_number, day_name, month_name, day_type, customer_tenure_segment, transaction_size_segment, spending_segment]
Index: []

[0 rows x 29 columns]

In [49]:
pd.read_sql("""SELECT MIN(transaction_amount) as maximum_amount,MAX(transaction_amount) as minimum_amount,AVG(transaction_amount) as average_amount 
FROM transactions_master ;""",engine)

   maximum_amount  minimum_amount  average_amount
0        2.582327    19486.987108     2402.199019

In [50]:
master_transaction['post_auth_risk_score'].describe()

count    400000.000000
mean          0.211365
std           0.142771
min           0.000001
25%           0.102100
50%           0.203767
75%           0.305576
max           0.999988
Name: post_auth_risk_score, dtype: float64

In [51]:
from sqlalchemy import text

# Correct way to run ALTER or UPDATE for new versions
with engine.begin() as conn:
    conn.execute(text("ALTER TABLE transactions_master ADD COLUMN risk_category VARCHAR(20) ;"))

In [52]:
# with engine.begin() as conn: use this format for creating tables,views updating or altering tables 
# to check windows function and joins you can use basic pd.read_sql

In [53]:
update_table = text(""" UPDATE  transactions_master 
                        SET risk_category = CASE
                        WHEN post_auth_risk_score < 0.203767 THEN 'Low_risk'
                        WHEN post_auth_risk_score >= 0.203767 AND post_auth_risk_score <0.400000 THEN 'Medium_risk'
                        ELSE 'High_risk'
                        END; """)
with engine.begin() as conn:
    conn.execute(update_table)
print("Table updated successfully")

Table updated successfully

In [54]:
pd.read_sql("SELECT post_auth_risk_score,risk_category FROM transactions_master LIMIT 10 ;",engine)

   post_auth_risk_score risk_category
0              0.099920      Low_risk
1              0.291715   Medium_risk
2              0.216647   Medium_risk
3              0.354154   Medium_risk
4              0.149084      Low_risk
5              0.290511   Medium_risk
6              0.220386   Medium_risk
7              0.032760      Low_risk
8              0.008795      Low_risk
9              0.293279   Medium_risk

In [55]:
with engine.begin() as conn:
    conn.execute(text("ALTER TABLE transactions_master ADD COLUMN velocity_risk VARCHAR(20) ;"))
print("Column created successfully ")

Column created successfully

In [56]:
update_column = text("""UPDATE transactions_master 
                        SET velocity_risk = CASE
                        WHEN txn_count_1h >= 7 OR txn_count_24h >= 12 OR failed_txn_count_24h >= 4 THEN 'Suspicious'
                        WHEN txn_count_1h BETWEEN 4 and 6 OR txn_count_24h between 7 and 11 OR failed_txn_count_24h BETWEEN 1 and 3 THEN 'Moderate'
                        ELSE 'Normal'
                        END ; """)
with engine.begin() as conn:
    conn.execute(update_column)
print("column updated successfully")

column updated successfully

In [57]:
pd.read_sql("SELECT velocity_risk FROM transactions_master LIMIT 10 ;",engine)

  velocity_risk
0      Moderate
1        Normal
2        Normal
3        Normal
4        Normal
5        Normal
6        Normal
7      Moderate
8        Normal
9        Normal

In [58]:
master_transaction[['is_international','ip_risk_score']].describe()

       is_international  ip_risk_score
count     400000.000000  400000.000000
mean           0.069487       0.285811
std            0.254282       0.160128
min            0.000000       0.000345
25%            0.000000       0.160781
50%            0.000000       0.264523
75%            0.000000       0.389497
max            1.000000       0.964121

In [59]:
with engine.begin() as conn:
    conn.execute(text("ALTER TABLE transactions_master ADD COLUMN international_risk_flag VARCHAR(30) ;"))
print("Column created successfully")

# 2. Update using the industry matrix logic
update_matrix = text("""
    UPDATE transactions_master 
    SET international_risk_flag = CASE
        WHEN is_international = 1 AND ip_risk_score >= 0.70 THEN 'Critical Risk'
        WHEN is_international = 1 AND ip_risk_score < 0.70 THEN 'Elevated Risk'
        WHEN is_international = 0 AND ip_risk_score >= 0.70 THEN 'Medium Risk'
        ELSE 'Low Risk'
    END;
""")

with engine.begin() as conn:
    conn.execute(update_matrix)
print("International risk flag populated successfully")

Column created successfully
International risk flag populated successfully

In [60]:
pd.read_sql("SELECT international_risk_flag FROM transactions_master LIMIT 5 ;",engine)

  international_risk_flag
0                Low Risk
1                Low Risk
2                Low Risk
3                Low Risk
4                Low Risk

In [61]:
master_transaction['merchant_risk_score'].describe()

count    400000.000000
mean          0.251343
std           0.146450
min           0.001365
25%           0.136028
50%           0.229556
75%           0.345401
max           0.837624
Name: merchant_risk_score, dtype: float64

In [62]:
with engine.begin() as conn:
    conn.execute(text("ALTER TABLE transactions_master ADD COLUMN merchant_risk_status VARCHAR(20) ;"))
print("column created")

column created

In [63]:
merchant_update = text("""UPDATE transactions_master
                          SET merchant_risk_status = CASE
                          WHEN merchant_risk_score < 0.229556 THEN 'Low Risk'
                          WHEN merchant_risk_score >=0.229556 AND merchant_risk_score<0.345401 THEN 'Medium Risk'
                          ELSE 'High Risk'
                          END ;""")
with engine.begin() as conn:
    conn.execute(merchant_update)
print("updated successfully")

updated successfully

In [64]:
with engine.begin() as conn:
    conn.execute(text("ALTER TABLE transactions_master ADD COLUMN fraud_severity VARCHAR(20) ;"))
print("Column fraud_severity created successfully")

update_severity = text("""
    UPDATE transactions_master 
    SET fraud_severity = CASE
        -- Calculate the weighted risk index score on the fly
        WHEN (post_auth_risk_score * 0.45 + merchant_risk_score * 0.35 + ip_risk_score * 0.20) >= 0.75 THEN 'Critical'
        WHEN (post_auth_risk_score * 0.45 + merchant_risk_score * 0.35 + ip_risk_score * 0.20) BETWEEN 0.50 AND 0.7499 THEN 'High'
        WHEN (post_auth_risk_score * 0.45 + merchant_risk_score * 0.35 + ip_risk_score * 0.20) BETWEEN 0.25 AND 0.4999 THEN 'Medium'
        ELSE 'Low'
    END;
""")

with engine.begin() as conn:
    conn.execute(update_severity)
print("Fraud severity tiers populated successfully")

Column fraud_severity created successfully
Fraud severity tiers populated successfully

In [65]:
# KPI analysis

In [66]:
Total_Transactions = pd.read_sql("SELECT COUNT(DISTINCT transaction_id) AS total_transactions FROM transactions_master ;",engine)
print(Total_Transactions)

   total_transactions
0              400000

In [67]:
Total_transaction_value = pd.read_sql("SELECT SUM(transaction_amount) AS total_value FROM transactions_master ;",engine)
print(Total_transaction_value)

    total_value
0  9.608796e+08

In [68]:
fraud = pd.read_sql("SELECT COUNT(*) AS fraud FROM transactions_master WHERE is_fraud = 1 ;",engine)
total_fraud_count = pd.read_sql("SELECT COUNT(is_fraud) AS total_count FROM transactions_master ;",engine)

In [69]:
fraud_count = fraud['fraud'].iloc[0]
total_fraud= total_fraud_count['total_count'].iloc[0]

Fraud_rate = (fraud_count/total_fraud)*100
print(f"Fraud Rate: {Fraud_rate:.2f}%")

Fraud Rate: 1.71%

In [70]:
Average_transaction = pd.read_sql("SELECT AVG(transaction_amount) AS average_transaction_value FROM transactions_master ;",engine)
print(Average_transaction)

   average_transaction_value
0                2402.199019

In [71]:
high_risk = pd.read_sql("SELECT count(*) as High_risk FROM transactions_master WHERE risk_category ='High_risk' ;",engine)
total_risk = pd.read_sql("SELECT COUNT(risk_category) AS total_risk FROM transactions_master ;",engine)

High_risk_count = high_risk['High_risk'].iloc[0]
Total_risk_count = total_risk['total_risk'].iloc[0]

High_Risk_Percentage = (High_risk_count/Total_risk_count)*100
print(f"HIGH RISK %: {High_Risk_Percentage:.2f}%")

HIGH RISK %: 1.71%

In [72]:
international = pd.read_sql("SELECT COUNT(*) as INTERNATIONAL FROM transactions_master WHERE is_international = 1 ;",engine)
total_int = pd.read_sql("SELECT COUNT(is_international) as INT_COUNT FROM transactions_master ;",engine)

INT_COUNT = international['INTERNATIONAL'].iloc[0]
TOTAL_INT_COUNT = total_int['INT_COUNT'].iloc[0]

International_Percentage =(INT_COUNT/TOTAL_INT_COUNT)*100
print(f"International Percentage : {International_Percentage :.2f}%")

International Percentage : 6.95%

#### FRAUD ANALYSIS

In [73]:
columns = pd.read_sql("DESCRIBE transactions_master ;",engine)
print(columns['Field'])

0                      transaction_id
1                    transaction_time
2                         customer_id
3                         merchant_id
4                    account_age_days
5                   credit_score_band
6                           kyc_level
7                   avg_monthly_spend
8                 merchant_risk_score
9                  transaction_amount
10                    payment_channel
11                        device_type
12                   is_international
13                      ip_risk_score
14                       txn_count_1h
15                      txn_count_24h
16               failed_txn_count_24h
17         geo_distance_from_last_txn
18    amount_deviation_from_user_mean
19                           is_fraud
20               post_auth_risk_score
21                               hour
22                         day_number
23                           day_name
24                         month_name
25                           day_type
26            customer_tenure_segment
27           transaction_size_segment
28                   spending_segment
29                      risk_category
30                      velocity_risk
31            international_risk_flag
32               merchant_risk_status
33                     fraud_severity
Name: Field, dtype: object

In [74]:
fraud_by_payment_method = pd.read_sql("""SELECT COUNT(is_fraud) AS fraud_count ,payment_channel FROM transactions_master
                                        WHERE is_fraud =1 GROUP BY payment_channel ORDER BY fraud_count DESC ;""",engine)
print(fraud_by_payment_method)

   fraud_count payment_channel
0         3451            card
1         1689             upi
2         1024          wallet
3          690   bank_transfer

In [75]:
fraud_by_hour =  pd.read_sql("""SELECT COUNT(is_fraud) AS fraud_count ,hour FROM transactions_master
                                        WHERE is_fraud =1 AND transaction_time is not null GROUP BY hour ORDER BY fraud_count DESC ;""",engine)
print(fraud_by_hour)

    fraud_count  hour
0           267  20.0
1           265  18.0
2           264  19.0
3           258   6.0
4           254  17.0
5           251   2.0
6           247   5.0
7           243   7.0
8           240  23.0
9           236  22.0
10          235  10.0
11          235  11.0
12          234   1.0
13          233   4.0
14          233  21.0
15          230  13.0
16          228  15.0
17          227   8.0
18          226  12.0
19          222  14.0
20          222   3.0
21          221  16.0
22          218   9.0
23          199   0.0

In [76]:
fraud_by_customer_tenure =  pd.read_sql("""SELECT COUNT(is_fraud) AS fraud_count ,customer_tenure_segment FROM transactions_master
                                        WHERE is_fraud =1 GROUP BY customer_tenure_segment ORDER BY fraud_count DESC ;""",engine)
print(fraud_by_customer_tenure)

   fraud_count customer_tenure_segment
0         4440      Long Term Customer
1         1261          Loyal Customer
2          937        Growing Customer
3          216            New Customer

In [77]:
fraud_by_merchant_risk =  pd.read_sql("""SELECT COUNT(is_fraud) AS fraud_count ,merchant_risk_status FROM transactions_master
                                        WHERE is_fraud =1 GROUP BY merchant_risk_status ORDER BY fraud_count DESC ;""",engine)

In [78]:
print(fraud_by_merchant_risk)

   fraud_count merchant_risk_status
0         3091             Low Risk
1         1987            High Risk
2         1776          Medium Risk

In [79]:
fraud_by_spending =  pd.read_sql("""SELECT COUNT(is_fraud) AS fraud_count ,spending_segment FROM transactions_master
                                        WHERE is_fraud =1 GROUP BY spending_segment ORDER BY fraud_count DESC ;""",engine)

print(fraud_by_spending)

   fraud_count           spending_segment
0         3059              Unusual spend
1         2011               Normal spend
2         1672       High deviation spend
3          112  Less than normal spending

In [80]:
riskiest_devices = pd.read_sql("""SELECT COUNT(*) AS total_transactions,SUM(is_fraud) AS total_fraud_cases,AVG(is_fraud)*100 AS fraud_rate_percentage
                                  ,device_type FROM transactions_master
                                  GROUP BY device_type ORDER BY fraud_rate_percentage DESC ;""",engine)

print(riskiest_devices)

   total_transactions  total_fraud_cases  fraud_rate_percentage device_type
0              279818             4804.0                 1.7168      mobile
1              100164             1716.0                 1.7132     desktop
2               20018              334.0                 1.6685      tablet

#### Customer analysis

In [81]:
TOP_SPENDERS = pd.read_sql("""SELECT customer_id,transaction_id,amount_deviation_from_user_mean,
                              DENSE_RANK() OVER (ORDER BY amount_deviation_from_user_mean DESC) AS spender_rank FROM transactions_master 
                              WHERE amount_deviation_from_user_mean > 0  ; """,engine)
print(TOP_SPENDERS.head(20))

    customer_id  transaction_id  amount_deviation_from_user_mean  spender_rank
0          2917           55810                     19419.022461             1
1          4776          374344                     19283.213352             2
2         29949          128614                     17291.983748             3
3         35089          178129                     16378.929893             4
4         26394            2685                     16373.115962             5
5         12947           16027                     16148.411470             6
6         15106          187684                     16017.972091             7
7          4193          154893                     15934.270936             8
8          8867           45603                     15879.350303             9
9          3602           29672                     15857.993228            10
10         9870          120855                     15830.096708            11
11         7372          187011                     15748.786755            12
12        31542          198406                     15584.901064            13
13        35349            5181                     15448.516044            14
14        37649           83212                     15405.401150            15
15        22610          148417                     15399.468053            16
16        33228          190061                     15373.646567            17
17        39635           95896                     15355.967821            18
18        18168           60844                     15162.789969            19
19         6914          365951                     15145.879250            20

In [82]:
HIGHEST_FRAUD_CUSTOMERS = pd.read_sql("""SELECT customer_id,COUNT(*) AS fraud_count FROM transactions_master 
                                         WHERE is_fraud =1 GROUP BY customer_id ORDER BY fraud_count DESC ; """,engine)
print(HIGHEST_FRAUD_CUSTOMERS.head(20))

    customer_id  fraud_count
0         19867            3
1         20779            3
2         11934            3
3          6634            3
4         19175            3
5         15792            3
6         20830            3
7         24191            3
8         33169            3
9         36444            3
10        14102            3
11        28192            3
12        39151            3
13         3294            3
14        35803            3
15        36818            3
16        16574            3
17        29854            3
18         7656            3
19        13680            3

In [83]:
Suspicious_Customers = pd.read_sql("""SELECT customer_id,transaction_id FROM transactions_master WHERE velocity_risk = 'Suspicious' ;""",engine)
print(Suspicious_Customers.head())

   customer_id  transaction_id
0         4248          328109
1        17956           11863
2        39360          130556
3         5036          243760
4         3581          363658

In [84]:
AVG_SPENT_BY_CUSTOMERS_SEGEMENT = pd.read_sql("""SELECT customer_tenure_segment,AVG(transaction_amount) AS average_spent
                                                 FROM transactions_master GROUP BY customer_tenure_segment
                                                ORDER BY average_spent DESC ;""",engine)
print(AVG_SPENT_BY_CUSTOMERS_SEGEMENT)

  customer_tenure_segment  average_spent
0            New Customer    2419.786864
1          Loyal Customer    2405.950238
2      Long Term Customer    2401.611308
3        Growing Customer    2395.861674

In [85]:
query_user_segmentation = """
    WITH user_geo_status AS (
        SELECT 
            customer_id,
            MAX(is_international) AS traveled_internationally
        FROM transactions_master
        GROUP BY customer_id
    )
   
    SELECT 
        CASE WHEN traveled_internationally = 1 THEN 'International User' ELSE 'Domestic User' END AS user_type,
        COUNT(*) AS total_users,
        (COUNT(*) / SUM(COUNT(*)) OVER()) * 100 AS user_percentage
    FROM user_geo_status
    GROUP BY traveled_internationally;
"""

df_user_geo = pd.read_sql(query_user_segmentation, engine)
print("--- Customer Geographic Segmentation ---")
print(df_user_geo)

--- Customer Geographic Segmentation ---
            user_type  total_users  user_percentage
0       Domestic User        19979          49.9487
1  International User        20020          50.0513

#### Merchant analysis

In [86]:
TOP_MERCHANT_BY_REVENUE = pd.read_sql("""SELECT merchant_id,SUM(transaction_amount) AS total_revenue FROM transactions_master
                                         GROUP BY merchant_id ORDER BY total_revenue DESC ; """,engine)
print(TOP_MERCHANT_BY_REVENUE.head(20))

    merchant_id  total_revenue
0          6737  211941.241616
1          1055  205867.301503
2          2753  204619.400179
3          7832  202708.746458
4          3259  201252.007186
5          7038  200539.293036
6          7926  196947.467657
7          3389  192768.340580
8          3801  191231.305387
9          7110  190760.335847
10         4749  189116.867538
11         7421  188550.692911
12         4351  187168.903964
13         4237  187166.629050
14          641  186716.495105
15         5192  185836.922230
16         5348  185770.109828
17          158  185588.267306
18            4  185010.863878
19         3433  184595.812001

In [87]:
Highest_Fraud_Merchant = pd.read_sql("""SELECT merchant_id,COUNT(*) AS fraud_count FROM transactions_master 
                                         WHERE is_fraud =1 GROUP BY merchant_id ORDER BY fraud_count DESC  ; """,engine)
print(Highest_Fraud_Merchant.head(20))

    merchant_id  fraud_count
0          4922            6
1          1604            5
2          3102            5
3          7120            5
4          7895            5
5          6147            5
6          7973            5
7          4396            5
8          1948            5
9          4200            5
10         7609            5
11         2180            5
12         6891            5
13         5092            5
14         5933            5
15         2933            4
16         7905            4
17         5137            4
18         4851            4
19         3048            4

In [88]:
Merchant_Fraud_Percent = pd.read_sql("""
    SELECT 
        merchant_id,
        COUNT(*) AS merchant_fraud_count,
        (COUNT(*) / SUM(COUNT(*)) OVER()) * 100 AS percentage_of_total_fraud
    FROM transactions_master
    WHERE is_fraud = 1
    GROUP BY merchant_id
    ORDER BY percentage_of_total_fraud DESC;
""", engine)

print("--- Merchant Share of Total Fraud ---")
print(Merchant_Fraud_Percent.head(10))

--- Merchant Share of Total Fraud ---
   merchant_id  merchant_fraud_count  percentage_of_total_fraud
0         4922                     6                     0.0875
1         1604                     5                     0.0730
2         3102                     5                     0.0730
3         7120                     5                     0.0730
4         7895                     5                     0.0730
5         6147                     5                     0.0730
6         7973                     5                     0.0730
7         4396                     5                     0.0730
8         1948                     5                     0.0730
9         4200                     5                     0.0730

In [89]:
merchant_performance = pd.read_sql("""SELECT merchant_id , SUM(transaction_amount)  AS total_revenue , AVG(is_fraud)*100 AS fraud_rate,
DENSE_RANK() OVER(ORDER BY SUM(transaction_amount) DESC) AS revenue_rank FROM transactions_master GROUP BY merchant_id;""",engine)
print(merchant_performance.head(10))

   merchant_id  total_revenue  fraud_rate  revenue_rank
0         6737  211941.241616        0.00             1
1         1055  205867.301503        1.32             2
2         2753  204619.400179        4.71             3
3         7832  202708.746458        0.00             4
4         3259  201252.007186        1.39             5
5         7038  200539.293036        2.86             6
6         7926  196947.467657        2.60             7
7         3389  192768.340580        1.54             8
8         3801  191231.305387        1.39             9
9         7110  190760.335847        0.00            10

#### payment analytics

In [90]:
BEST_PERFORMING_PAYMENT_CHANNEL = pd.read_sql("""SELECT payment_channel,SUM(transaction_amount) AS total_payment
                                                FROM transactions_master GROUP BY payment_channel ORDER BY total_payment DESC""",engine)
top_channel = BEST_PERFORMING_PAYMENT_CHANNEL['payment_channel'].iloc[0]
top_value = BEST_PERFORMING_PAYMENT_CHANNEL['total_payment'].iloc[0]

print(f"BEST PERFORMING CHANNEL: {top_channel} (${top_value:,.2f})")

BEST PERFORMING CHANNEL: card ($480,214,455.49)

In [91]:
Fraud_rate_by_channel = pd.read_sql("""SELECT payment_channel,avg(is_fraud)*100 AS fraud_rate FROM transactions_master
                                        GROUP BY payment_channel ; """,engine)
print(Fraud_rate_by_channel)

  payment_channel  fraud_rate
0          wallet      1.7018
1   bank_transfer      1.7262
2            card      1.7280
3             upi      1.6865

In [92]:
AVG_transaction_by_channel = pd.read_sql("""SELECT payment_channel,avg(transaction_amount) AS average_transaction FROM transactions_master
                                        GROUP BY payment_channel ; """,engine)
print(AVG_transaction_by_channel)

  payment_channel  average_transaction
0          wallet          2394.513326
1   bank_transfer          2406.263291
2            card          2404.582969
3             upi          2400.440628

In [93]:
International_transactions_by_payment_channel = pd.read_sql("""SELECT payment_channel,SUM(transaction_amount) AS total_payment
                                                                FROM transactions_master WHERE is_international =1 
                                                                GROUP BY payment_channel ORDER BY total_payment DESC;""",engine)
print(International_transactions_by_payment_channel)

  payment_channel  total_payment
0            card   3.344589e+07
1             upi   1.701917e+07
2          wallet   9.544477e+06
3   bank_transfer   6.750359e+06

#### Time analysis

In [94]:
peak_transaction_hours = pd.read_sql(""" SELECT hour,SUM(transaction_amount) AS total_transaction FROM transactions_master WHERE hour is not null GROUP BY hour
                               ORDER BY total_transaction DESC ;""",engine)    

print('PEAK TRANSACTION HOURS') 
print(peak_transaction_hours.head(5))

PEAK TRANSACTION HOURS
   hour  total_transaction
0  12.0       3.477188e+07
1   1.0       3.476552e+07
2   6.0       3.467446e+07
3  20.0       3.457916e+07
4  21.0       3.449893e+07

In [95]:
peak_fraud_hours =  pd.read_sql("""SELECT COUNT(is_fraud) AS fraud_count ,hour FROM transactions_master
                                        WHERE is_fraud =1 AND transaction_time is not null 
                                        GROUP BY hour ORDER BY fraud_count DESC  ;""",engine)
print('Peak fraud hours')
print(peak_fraud_hours.head(5))

Peak fraud hours
   fraud_count  hour
0          267  20.0
1          265  18.0
2          264  19.0
3          258   6.0
4          254  17.0

In [96]:
WEEKENDvsWEEKDAY_transactions = pd.read_sql("""SELECT day_type,SUM(transaction_amount) AS total_payment ,AVG(transaction_amount) AS avg_payment,
               (SUM(transaction_amount)/SUM(SUM(transaction_amount)) OVER () )*100 AS spending_percentage
               FROM transactions_master GROUP BY day_type ;""",engine)
print(WEEKENDvsWEEKDAY_transactions)

  day_type  total_payment  avg_payment  spending_percentage
0  Weekend   2.051343e+08  2398.810868            21.348597
1  Weekday   7.557453e+08  2403.120327            78.651403

In [97]:
Hourly_Trend = pd.read_sql("""
    SELECT 
        hour,
        SUM(transaction_amount) AS total_sales,
        SUM(is_fraud) AS total_fraud_cases
    FROM transactions_master
    WHERE hour IS NOT NULL
    GROUP BY hour
    ORDER BY hour ASC;
""", engine)

print(Hourly_Trend)

    hour   total_sales  total_fraud_cases
0    0.0  3.394812e+07              199.0
1    1.0  3.476552e+07              234.0
2    2.0  3.416335e+07              251.0
3    3.0  3.413233e+07              222.0
4    4.0  3.395413e+07              233.0
5    5.0  3.369771e+07              247.0
6    6.0  3.467446e+07              258.0
7    7.0  3.373670e+07              243.0
8    8.0  3.401995e+07              227.0
9    9.0  3.407821e+07              218.0
10  10.0  3.398490e+07              235.0
11  11.0  3.338504e+07              235.0
12  12.0  3.477188e+07              226.0
13  13.0  3.361591e+07              230.0
14  14.0  3.397595e+07              222.0
15  15.0  3.408097e+07              228.0
16  16.0  3.384834e+07              221.0
17  17.0  3.339289e+07              254.0
18  18.0  3.360547e+07              265.0
19  19.0  3.412476e+07              264.0
20  20.0  3.457916e+07              267.0
21  21.0  3.449893e+07              233.0
22  22.0  3.399687e+07              236.0
23  23.0  3.404176e+07              240.0

In [98]:
#making copy of sql data 
master_transaction_2 = pd.read_sql("SELECT * FROM transactions_master",engine)

## Views for tableu

In [99]:
customer_summary_view = text("""

CREATE OR REPLACE VIEW customer_summary AS

SELECT
    customer_id,

    -- Customer profile
    MAX(account_age_days) AS account_age_days,
    MAX(credit_score_band) AS credit_score_band,
    MAX(kyc_level) AS kyc_level,

    -- Transaction activity
    COUNT(transaction_id) AS total_transactions,
    ROUND(SUM(transaction_amount),2) AS total_payment,
    ROUND(AVG(transaction_amount),2) AS average_payment,
    ROUND(AVG(avg_monthly_spend),2) AS avg_monthly_spent,

    -- Fraud metrics
    SUM(is_fraud) AS total_fraud_cases,
    ROUND(
        (SUM(is_fraud) * 100.0) /
        COUNT(transaction_id), 2
    ) AS fraud_rate_percent,

    ROUND(AVG(post_auth_risk_score),2)
        AS avg_post_auth_risk,

    MAX(post_auth_risk_score)
        AS highest_post_auth_risk,

    -- International behavior
    SUM(is_international)
        AS total_international_transactions,

    CASE
        WHEN SUM(is_international) > 0
        THEN 'Yes'
        ELSE 'No'
    END AS traveled_internationally,

    -- Customer behavior
    MAX(failed_txn_count_24h)
        AS max_failed_txn_per_day,

    ROUND(MAX(geo_distance_from_last_txn),2)
        AS max_geo_distance,

    MAX(transaction_amount)
        AS highest_transaction,

    ROUND(AVG(amount_deviation_from_user_mean),2)
        AS avg_spending_deviation,

    -- Time activity
    MAX(transaction_time)
        AS last_transaction_time,

    -- Highest fraud severity (business order)
    CASE
        WHEN MAX(
            CASE
                WHEN fraud_severity = 'Critical' THEN 4
                WHEN fraud_severity = 'High' THEN 3
                WHEN fraud_severity = 'Medium' THEN 2
                ELSE 1
            END
        ) = 4 THEN 'Critical'

        WHEN MAX(
            CASE
                WHEN fraud_severity = 'Critical' THEN 4
                WHEN fraud_severity = 'High' THEN 3
                WHEN fraud_severity = 'Medium' THEN 2
                ELSE 1
            END
        ) = 3 THEN 'High'

        WHEN MAX(
            CASE
                WHEN fraud_severity = 'Critical' THEN 4
                WHEN fraud_severity = 'High' THEN 3
                WHEN fraud_severity = 'Medium' THEN 2
                ELSE 1
            END
        ) = 2 THEN 'Medium'

        ELSE 'Low'
    END AS highest_fraud_severity,

    CASE
    WHEN MAX(
        CASE
            WHEN customer_tenure_segment = 'New Customer' THEN 1
            WHEN customer_tenure_segment = 'Growing Customer' THEN 2
            WHEN customer_tenure_segment = 'Loyal Customer' THEN 3
            WHEN customer_tenure_segment = 'Long-Term Customer' THEN 4
        END
    ) = 4 THEN 'Long-Term Customer'

    WHEN MAX(
        CASE
            WHEN customer_tenure_segment = 'New Customer' THEN 1
            WHEN customer_tenure_segment = 'Growing Customer' THEN 2
            WHEN customer_tenure_segment = 'Loyal Customer' THEN 3
            WHEN customer_tenure_segment = 'Long-Term Customer' THEN 4
        END
    ) = 3 THEN 'Loyal Customer'

    WHEN MAX(
        CASE
            WHEN customer_tenure_segment = 'New Customer' THEN 1
            WHEN customer_tenure_segment = 'Growing Customer' THEN 2
            WHEN customer_tenure_segment = 'Loyal Customer' THEN 3
            WHEN customer_tenure_segment = 'Long-Term Customer' THEN 4
        END
    ) = 2 THEN 'Growing Customer'

    ELSE 'New Customer'
END AS customer_tenure_segment,

    -- Highest velocity risk
    CASE
        WHEN MAX(
            CASE
                WHEN velocity_risk = 'Suspicious' THEN 3
                WHEN velocity_risk = 'Moderate' THEN 2
                ELSE 1
            END
        ) = 3 THEN 'Suspicious'

        WHEN MAX(
            CASE
                WHEN velocity_risk = 'Suspicious' THEN 3
                WHEN velocity_risk = 'Moderate' THEN 2
                ELSE 1
            END
        ) = 2 THEN 'Moderate'

        ELSE 'Normal'
    END AS highest_velocity_risk
    

FROM transactions_master
GROUP BY customer_id ;
""")

with engine.begin() as conn:
    conn.execute(customer_summary_view)

print("customer_summary view created successfully")

customer_summary view created successfully

In [100]:
fraud_analysis_view = text("""
CREATE OR REPLACE VIEW fraud_analysis AS

SELECT
    -- IDs
    transaction_id,
    customer_id,
    merchant_id,

    -- Time
    transaction_time,
    hour,
    day_name,
    month_name,
    day_type,

    -- Transaction Details
    transaction_amount,
    transaction_size_segment,
    payment_channel,
    device_type,
    is_international,

    -- Fraud & Risk
    is_fraud,
    fraud_severity,
    risk_category,
    velocity_risk,
    international_risk_flag,
    merchant_risk_status,

    -- Risk Scores
    post_auth_risk_score,
    merchant_risk_score,
    ip_risk_score,

    -- Behavioral Signals
    txn_count_1h,
    txn_count_24h,
    failed_txn_count_24h,
    geo_distance_from_last_txn,
    amount_deviation_from_user_mean,
    spending_segment,

    -- Customer Segmentation
    customer_tenure_segment,
    credit_score_band,
    kyc_level

FROM transactions_master; """)
with engine.begin() as conn:
    conn.execute(fraud_analysis_view)

print("fraud_analysis view created successfully")

fraud_analysis view created successfully

In [101]:
merchant_analysis = text("""
CREATE OR REPLACE VIEW merchant_performance AS

SELECT
    merchant_id,

    -- Transaction KPIs
    COUNT(transaction_id) AS total_transactions,

    ROUND(SUM(transaction_amount),2)
        AS total_revenue,

    ROUND(AVG(transaction_amount),2)
        AS average_transaction_value,

    COUNT(DISTINCT customer_id)
        AS total_unique_customers,

    -- Fraud KPIs
    SUM(is_fraud)
        AS fraud_transactions,

    ROUND(
        (SUM(is_fraud) * 100.0) /
        COUNT(transaction_id),2
    ) AS fraud_rate_percent,

    -- Risk Metrics
    ROUND(AVG(merchant_risk_score),2)
        AS avg_merchant_risk_score,

    MAX(merchant_risk_score)
        AS max_merchant_risk_score,

    MAX(merchant_risk_status)
        AS merchant_risk_status,

    ROUND(AVG(post_auth_risk_score),2)
        AS avg_post_auth_risk,

    ROUND(AVG(ip_risk_score),2)
        AS avg_ip_risk_score,

    -- International Behavior
    SUM(is_international)
        AS international_transaction_count,

    -- Operational Metrics
    ROUND(AVG(failed_txn_count_24h),2)
        AS avg_failed_transactions,

    ROUND(AVG(geo_distance_from_last_txn),2)
        AS avg_geo_distance,

    -- Highest Fraud Severity
    CASE
        WHEN MAX(
            CASE
                WHEN fraud_severity = 'Critical' THEN 4
                WHEN fraud_severity = 'High' THEN 3
                WHEN fraud_severity = 'Medium' THEN 2
                ELSE 1
            END
        ) = 4 THEN 'Critical'

        WHEN MAX(
            CASE
                WHEN fraud_severity = 'Critical' THEN 4
                WHEN fraud_severity = 'High' THEN 3
                WHEN fraud_severity = 'Medium' THEN 2
                ELSE 1
            END
        ) = 3 THEN 'High'

        WHEN MAX(
            CASE
                WHEN fraud_severity = 'Critical' THEN 4
                WHEN fraud_severity = 'High' THEN 3
                WHEN fraud_severity = 'Medium' THEN 2
                ELSE 1
            END
        ) = 2 THEN 'Medium'

        ELSE 'Low'
    END AS highest_fraud_severity,

    -- Ranking
    RANK() OVER (
        ORDER BY SUM(transaction_amount) DESC
    ) AS merchant_revenue_rank

FROM transactions_master
GROUP BY merchant_id;""")
with engine.begin() as conn:
    conn.execute(merchant_analysis)
print('merchant analysis view created successfully')

merchant analysis view created successfully

In [102]:
kpis_view = text("""
CREATE OR REPLACE VIEW executive_kpis AS

SELECT

    -- Financial KPIs
    COUNT(transaction_id)
        AS total_transactions,

    ROUND(SUM(transaction_amount),2)
        AS total_transaction_value,

    ROUND(AVG(transaction_amount),2)
        AS average_transaction_value,

    -- Fraud KPIs
    SUM(is_fraud)
        AS total_fraud_cases,

    ROUND(
        (SUM(is_fraud) * 100.0) /
        COUNT(transaction_id),2
    ) AS fraud_rate_percent,

    SUM(
        CASE
            WHEN fraud_severity = 'Critical'
            THEN 1
            ELSE 0
        END
    ) AS critical_transactions,

    SUM(
        CASE
            WHEN risk_category = 'High_risk'
            THEN 1
            ELSE 0
        END
    ) AS high_risk_transactions,

    -- Customer KPIs
    COUNT(DISTINCT customer_id)
        AS total_customers,

    ROUND(
        SUM(transaction_amount)
        /
        COUNT(DISTINCT customer_id),2
    ) AS avg_customer_spend,

    COUNT(
        DISTINCT CASE
            WHEN is_international = 1
            THEN customer_id
        END
    ) AS international_customers,

    -- Merchant KPIs
    COUNT(DISTINCT merchant_id)
        AS total_merchants,

    COUNT(
        DISTINCT CASE
            WHEN merchant_risk_status = 'High Risk'
            THEN merchant_id
        END
    ) AS high_risk_merchants,

    -- Most Used Payment Channel
    (
        SELECT payment_channel
        FROM transactions_master
        GROUP BY payment_channel
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ) AS most_used_payment_channel,

    -- Peak Transaction Hour
    (
        SELECT hour
        FROM transactions_master
        where hour is not null
        GROUP BY hour
        ORDER BY COUNT(*) DESC
        LIMIT 1
    ) AS peak_transaction_hour,

    -- Peak Fraud Hour
    (
        SELECT hour
        FROM transactions_master
        WHERE is_fraud = 1 and hour is not null
        GROUP BY hour
        ORDER BY COUNT(is_fraud) DESC
        LIMIT 1
    ) AS peak_fraud_hour

FROM transactions_master;""")
with engine.begin() as conn:
    conn.execute(kpis_view)
print('executive kpi view created successfully')

executive kpi view created successfully

#### validating views

In [103]:
pd.read_sql("SELECT * FROM customer_summary LIMIT 5;",engine)

,customer_id,account_age_days,credit_score_band,kyc_level,total_transactions,total_payment,average_payment,avg_monthly_spent,total_fraud_cases,fraud_rate_percent,...,total_international_transactions,traveled_internationally,max_failed_txn_per_day,max_geo_distance,highest_transaction,avg_spending_deviation,last_transaction_time,highest_fraud_severity,customer_tenure_segment,highest_velocity_risk
0,0,255,5,2,11,23083.58,2098.51,3434.93,0.0,0.0,...,1.0,Yes,1,69.93,4730.401527,1984.01,2023-07-01 15:54:36,Medium,Growing Customer,Moderate
1,1,1132,3,2,10,16554.26,1655.43,4495.67,0.0,0.0,...,1.0,Yes,1,94.21,5130.326499,1505.57,2026-05-20 12:22:30,Medium,New Customer,Moderate
2,2,473,3,3,5,22385.11,4477.02,3683.15,0.0,0.0,...,1.0,Yes,1,65.88,8401.631280,4354.25,2026-05-20 14:14:30,Medium,Loyal Customer,Moderate
3,3,737,1,1,11,15456.04,1405.09,14103.16,0.0,0.0,...,1.0,Yes,1,76.47,2848.219631,934.99,2026-05-20 05:26:36,Medium,New Customer,Moderate
4,4,1633,2,2,4,6323.20,1580.80,2450.78,0.0,0.0,...,0.0,No,2,81.64,3035.597554,1499.11,2026-05-20 22:17:42,Medium,New Customer,Moderate

In [104]:
pd.read_sql("SELECT * FROM fraud_analysis LIMIT 5",engine)

,transaction_id,customer_id,merchant_id,transaction_time,hour,day_name,month_name,day_type,transaction_amount,transaction_size_segment,...,ip_risk_score,txn_count_1h,txn_count_24h,failed_txn_count_24h,geo_distance_from_last_txn,amount_deviation_from_user_mean,spending_segment,customer_tenure_segment,credit_score_band,kyc_level
0,359131,11102,2282,2023-01-01 00:02:00,0.0,Sunday,January,Weekend,2408.320473,Large,...,0.142532,1,3,1,33.458018,2205.262235,Unusual spend,Growing Customer,2,3
1,351207,22891,3016,2023-01-01 00:02:26,0.0,Sunday,January,Weekend,2765.255095,Large,...,0.131811,0,5,0,3.375083,2638.786943,Unusual spend,Long Term Customer,2,3
2,10209,3102,1855,2023-01-01 00:06:54,0.0,Sunday,January,Weekend,1529.079168,Medium,...,0.322137,0,5,0,13.732603,1305.843886,Unusual spend,Long Term Customer,5,2
3,62660,4041,2525,2023-01-01 00:06:58,0.0,Sunday,January,Weekend,610.407487,Small,...,0.171764,1,2,0,18.840187,513.517097,Normal spend,Long Term Customer,1,1
4,384254,3979,1555,2023-01-01 00:08:05,0.0,Sunday,January,Weekend,986.397163,Small,...,0.248766,1,1,0,15.344375,816.975430,Normal spend,Growing Customer,2,3

In [105]:
pd.read_sql("SELECT * FROM merchant_performance LIMIT 5",engine)

,merchant_id,total_transactions,total_revenue,average_transaction_value,total_unique_customers,fraud_transactions,fraud_rate_percent,avg_merchant_risk_score,max_merchant_risk_score,merchant_risk_status,avg_post_auth_risk,avg_ip_risk_score,international_transaction_count,avg_failed_transactions,avg_geo_distance,highest_fraud_severity,merchant_revenue_rank
0,6737,74,211941.24,2864.07,74,0.0,0.00,0.22,0.224941,Low Risk,0.20,0.27,5.0,0.49,34.58,Medium,1
1,1055,76,205867.30,2708.78,76,1.0,1.32,0.27,0.270992,Medium Risk,0.22,0.28,5.0,0.37,35.06,High,2
2,2753,85,204619.40,2407.29,85,4.0,4.71,0.29,0.294032,Medium Risk,0.24,0.28,6.0,0.35,36.01,High,3
3,7832,79,202708.75,2565.93,79,0.0,0.00,0.15,0.151243,Low Risk,0.20,0.30,3.0,0.35,36.97,Medium,4
4,3259,72,201252.01,2795.17,71,1.0,1.39,0.35,0.350907,High Risk,0.20,0.28,3.0,0.29,35.88,High,5

In [106]:
pd.read_sql("SELECT * FROM executive_kpis",engine)

,total_transactions,total_transaction_value,average_transaction_value,total_fraud_cases,fraud_rate_percent,critical_transactions,high_risk_transactions,total_customers,avg_customer_spend,international_customers,total_merchants,high_risk_merchants,most_used_payment_channel,peak_transaction_hour,peak_fraud_hour
0,400000,9.608796e+08,2402.2,6854.0,1.71,29.0,6856.0,39999,24022.59,20020,8000,2002,card,20.0,20.0

In [107]:
pd.read_sql('SELECT count(distinct customer_id) FROM transactions_master',engine)

   count(distinct customer_id)
0                        39999

In [108]:
pd.read_sql('select count(*) from customer_summary',engine)

   count(*)
0     39999

In [109]:
fraud_analysis = pd.read_sql('SELECT * FROM fraud_analysis',engine)

In [110]:
fraud_analysis.shape

(400000, 31)

In [113]:
# our fraud analysis is too large to export from sql so we will export it from here

In [112]:
fraud_analysis.head(5)

,transaction_id,customer_id,merchant_id,transaction_time,hour,day_name,month_name,day_type,transaction_amount,transaction_size_segment,...,ip_risk_score,txn_count_1h,txn_count_24h,failed_txn_count_24h,geo_distance_from_last_txn,amount_deviation_from_user_mean,spending_segment,customer_tenure_segment,credit_score_band,kyc_level
0,359131,11102,2282,2023-01-01 00:02:00,0.0,Sunday,January,Weekend,2408.320473,Large,...,0.142532,1,3,1,33.458018,2205.262235,Unusual spend,Growing Customer,2,3
1,351207,22891,3016,2023-01-01 00:02:26,0.0,Sunday,January,Weekend,2765.255095,Large,...,0.131811,0,5,0,3.375083,2638.786943,Unusual spend,Long Term Customer,2,3
2,10209,3102,1855,2023-01-01 00:06:54,0.0,Sunday,January,Weekend,1529.079168,Medium,...,0.322137,0,5,0,13.732603,1305.843886,Unusual spend,Long Term Customer,5,2
3,62660,4041,2525,2023-01-01 00:06:58,0.0,Sunday,January,Weekend,610.407487,Small,...,0.171764,1,2,0,18.840187,513.517097,Normal spend,Long Term Customer,1,1
4,384254,3979,1555,2023-01-01 00:08:05,0.0,Sunday,January,Weekend,986.397163,Small,...,0.248766,1,1,0,15.344375,816.975430,Normal spend,Growing Customer,2,3

In [114]:
fraud_analysis.to_csv(r'E:\updateresumeprojects\SQL+pandaspipeline project\Exported files\fraud_analysis.csv' , index = False)